//Event is like sending some signal
//like when we press on a button some function will be executed
//Event is generated by event emitter
//Here button is event emitter
//In node button click can be created with api's.
//we can't create them directly like in html and js.

const express = require('express')
const app = express()
const EventEmitter = require('events')   //EventEmitter is a class
const event = new EventEmitter()

let count = 0
event.on("countAPI",()=>{   //takes two parameters event name, cb
    count++
    console.log('event emitted', count)
})


app.get('/', (req,res)=>{
    res.send('api called')
    event.emit("countAPI")

})

app.get('/search', (req,res)=>{
    res.send('search api called')
    event.emit("countAPI")
})

app.get('/update', (req,res)=>{
    res.send('update api called')
    event.emit("countAPI")
})

app.listen(5000)